// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 7/30/2025, 11:59:31 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/rish/Developer/Pravis-Boutique/frontend/pravis-boutique/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/rish/Developer/Pravis-Boutique/frontend/pravis-boutique/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/rish/Developer/Pravis-Boutique/frontend/pravis-boutique/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/rish/Developer/Pravis-Boutique/frontend/pravis-boutique/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/rish/Developer/Pravis-Boutique/frontend/pravis-boutique/plugins/**/*.{js,ts,mjs}","/Users/rish/Developer/Pravis-Boutique/frontend/pravis-boutique/composables/**/*.{js,ts,mjs}","/Users/rish/Developer/Pravis-Boutique/frontend/pravis-boutique/utils/**/*.{js,ts,mjs}","/Users/rish/Developer/Pravis-Boutique/frontend/pravis-boutique/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/rish/Developer/Pravis-Boutique/frontend/pravis-boutique/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/rish/Developer/Pravis-Boutique/frontend/pravis-boutique/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/rish/Developer/Pravis-Boutique/frontend/pravis-boutique/app.config.{js,ts,mjs}"]}},
{"theme":{"extend":{"fontFamily":{"display":["Playfair Display","serif"],"body":["Inter","sans-serif"]},"colors":{"pravis":{"50":"#fdf2f8","100":"#fce7f3","200":"#fbcfe8","300":"#f9a8d4","400":"#f472b6","500":"#8B0000","600":"#A0001C","700":"#7F0000","800":"#5F0000","900":"#3F0000"},"gold":{"50":"#fffbeb","100":"#fef3c7","200":"#fde68a","300":"#fcd34d","400":"#fbbf24","500":"#D4AF37","600":"#B8860B","700":"#996F00","800":"#7A5600","900":"#5B4000"}}}}},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;