// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 8/14/2025, 7:00:07 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/home/runner/work/Pravis-Boutique/Pravis-Boutique/frontend/pravis-boutique/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/runner/work/Pravis-Boutique/Pravis-Boutique/frontend/pravis-boutique/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/runner/work/Pravis-Boutique/Pravis-Boutique/frontend/pravis-boutique/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/runner/work/Pravis-Boutique/Pravis-Boutique/frontend/pravis-boutique/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/runner/work/Pravis-Boutique/Pravis-Boutique/frontend/pravis-boutique/plugins/**/*.{js,ts,mjs}","/home/runner/work/Pravis-Boutique/Pravis-Boutique/frontend/pravis-boutique/composables/**/*.{js,ts,mjs}","/home/runner/work/Pravis-Boutique/Pravis-Boutique/frontend/pravis-boutique/utils/**/*.{js,ts,mjs}","/home/runner/work/Pravis-Boutique/Pravis-Boutique/frontend/pravis-boutique/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/runner/work/Pravis-Boutique/Pravis-Boutique/frontend/pravis-boutique/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/runner/work/Pravis-Boutique/Pravis-Boutique/frontend/pravis-boutique/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/runner/work/Pravis-Boutique/Pravis-Boutique/frontend/pravis-boutique/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;