// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/analytics/event': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/analytics/event.post').default>>>>
    }
    '/api/push-notifications/send': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/push-notifications/send').default>>>>
    }
    '/api/push-subscriptions': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/push-subscriptions/index').default>>>>
    }
    '/api/user/delete-data': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user/delete-data.delete').default>>>>
    }
    '/api/user/export-data': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user/export-data.post').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
    '/_ipx/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/image/dist/runtime/ipx').default>>>>
    }
  }
}
export {}