<template>
  <div>
    <div class="container mx-auto px-4 py-16">
      <div class="max-w-4xl mx-auto bg-white rounded-lg shadow-lg p-8">
        <div class="text-center mb-8">
          <h1 class="font-display text-4xl font-bold text-gray-800 mb-4">
            Terms of Service
          </h1>
          <p class="text-gray-600">
            Last updated: {{ lastUpdated }}
          </p>
        </div>

        <div class="prose prose-lg max-w-none">
          <h2>1. Introduction</h2>
          <p>
            Welcome to Pravis Boutique. These Terms of Service ("Terms") govern your use of our AI-powered fashion shopping platform, including our voice agent "Ask Pravi".
          </p>

          <h2>2. AI Voice Agent</h2>
          <p>
            Our voice agent "Ask Pravi" is an AI-powered assistant designed to help you with fashion recommendations and shopping assistance. By using this service, you understand that:
          </p>
          <ul>
            <li>Voice interactions may be recorded for training and improvement purposes</li>
            <li>The AI provides suggestions based on your preferences and data</li>
            <li>Recommendations are generated by AI and may not always reflect personal taste</li>
          </ul>

          <h2>3. Data Collection and Privacy</h2>
          <p>
            We collect and process data in accordance with our Privacy Policy. This includes:
          </p>
          <ul>
            <li>Voice recordings and transcriptions</li>
            <li>User preferences and shopping behavior</li>
            <li>Device and usage analytics</li>
          </ul>

          <h2>4. User Responsibilities</h2>
          <p>You agree to:</p>
          <ul>
            <li>Provide accurate information when interacting with our services</li>
            <li>Use the voice agent respectfully and appropriately</li>
            <li>Not attempt to reverse engineer or misuse our AI technology</li>
          </ul>

          <h2>5. Service Availability</h2>
          <p>
            We strive to provide continuous service but cannot guarantee 100% uptime. Voice recognition and AI features may have occasional limitations or errors.
          </p>

          <h2>6. Intellectual Property</h2>
          <p>
            All content, including AI responses, recommendations, and platform features, are the property of Pravis Boutique and protected by intellectual property laws.
          </p>

          <h2>7. Limitation of Liability</h2>
          <p>
            Pravis Boutique is not liable for any damages resulting from AI recommendations, voice recognition errors, or service interruptions.
          </p>

          <h2>8. Changes to Terms</h2>
          <p>
            We may update these terms periodically. Continued use of our service after changes constitutes acceptance of new terms.
          </p>

          <h2>9. Contact Information</h2>
          <p>
            For questions about these terms, please contact us at legal@pravisboutique.com
          </p>
        </div>

        <div class="mt-8 pt-8 border-t text-center">
          <button
            class="btn-primary px-6 py-3"
            @click="goBack"
          >
            ← Back to Boutique
          </button>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  name: 'TermsPage',
  data () {
    return {
      lastUpdated: new Date().toLocaleDateString('en-US', {
        year: 'numeric',
        month: 'long',
        day: 'numeric'
      })
    }
  },
  head () {
    return {
      title: 'Terms of Service - Pravis Boutique',
      meta: [
        {
          hid: 'description',
          name: 'description',
          content: 'Terms of Service for Pravis Boutique AI-powered fashion platform and Ask Pravi voice agent.'
        }
      ]
    }
  },
  methods: {
    goBack () {
      this.$router.go(-1)
    }
  }
}
</script>

<style scoped>
.prose {
  color: #374151;
}

.prose h2 {
  color: #1f2937;
  font-weight: 700;
  margin-top: 2rem;
  margin-bottom: 1rem;
}

.prose p {
  margin-bottom: 1rem;
  line-height: 1.7;
}

.prose ul {
  margin: 1rem 0;
  padding-left: 1.5rem;
}

.prose li {
  margin-bottom: 0.5rem;
}
</style>
